name: Deploy React App

on:
  push:
    branches:
      - main # เปลี่ยนเป็น branch ที่คุณต้องการ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Build Docker image
        run: docker build -t my-react-app .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-react-app ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "jjsornwakii.3bbddns.com"
          username: "jj"
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: "34722"
          script: |
            docker pull my-react-app
            docker stop my-react-container || true
            docker rm my-react-container || true
            docker run -d -p 3000:80 --name my-react-container my-react-app
