name: Deploy React App

on:
  push:
    branches:
      - main # เปลี่ยนเป็น branch ที่คุณต้องการ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Build Docker image
        run: docker build -t my-react-app .

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push my-react-app

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            docker pull my-react-app
            docker stop my-react-container || true
            docker rm my-react-container || true
            docker run -d -p 3000:80 --name my-react-container my-react-app